<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>stis_help_bot</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
      <PackageReference Include="PuppeteerSharp" Version="8.0.0" />
      <PackageReference Include="Spire.PDF" Version="8.12.5" />
      <PackageReference Include="Telegram.Bot" Version="19.0.0-preview.1" />
    </ItemGroup>

</Project>
